[package]
name = "clap-derive"
description = "Custom derives for Clap"
version = "0.0.6"
authors = [
	"hoverbear <andrew@hoverbear.org>",
	"Guillaume Pinot <texitoi@texitoi.eu>",
	"Kevin K. <kbknapp@gmail.com>"
]
license = "MIT/Apache-2.0"
categories = ["command-line-interface"]
keywords = ["macro", "clap", "command-line", "structopt", "derive"]
readme = "README.md"
repository = "https://github.com/kbknapp/clap-derives"

[badges]
travis-ci = { repository = "https://github.com/kbknapp/clap-derives" }
appveyor = { repository = "https://github.com/kbknapp/clap-derives", service = "github" }

[workspace]

[dependencies]
clap = "2"
clippy    = { version = "~0.0.166", optional = true }

[dev-dependencies]
clap-derive-internals = {path = "clap-derive-internals/"}

[features]
default     = []
unstable    = [] # for building with unstable clap features (doesn't require nightly Rust) 
nightly     = [] # for building with unstable Rust features 
lints       = ["clippy"] # Requires nightly Rust

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
# codegen-units ignored with lto=true

[profile.dev]
opt-level = 0
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 4

[profile.test]
opt-level = 1
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 4

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false

[profile.doc]
opt-level = 0
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 4

[package.metadata.docs.rs]
features = ["doc"]